steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform:1.8"
    entrypoint: "terraform"
    args: ["init"]
    dir: "terraform"

  # Step 2: Run the command passed from the trigger ('plan' or 'apply')
  - name: "hashicorp/terraform:1.8"
    entrypoint: "terraform"
    # Uses substitution variables that will be sent by the Infra Agent's API call
    args:
      - "${_COMMAND}"
      - "-var=project_id=${PROJECT_ID}"
      - "-var=region=${_REGION}"
      - "-var=service_name=${_SERVICE_NAME}"
      - "-var=image_uri=${_IMAGE_URI}"
      - "-no-color" # Good for clean logs
    dir: "terraform"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
