steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform:1.12.1"
    entrypoint: "terraform"
    args: ["init"]
    dir: "terraform"

  # Step 1.5: Debug - Show what command will be executed
  - name: "hashicorp/terraform:1.12.1"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Command to execute: ${_COMMAND}"
        echo "Project ID: ${PROJECT_ID}"
        echo "Region: ${_REGION}"
        echo "Service Name: ${_SERVICE_NAME}"
        echo "Image URI: ${_IMAGE_URI}"
        terraform --version
    dir: "terraform"

  # Step 2: Run terraform command with proper argument handling
  - name: "hashicorp/terraform:1.12.1"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ "${_COMMAND}" = "plan" ]; then
          terraform plan -var="project_id=${PROJECT_ID}" -var="region=${_REGION}" -var="service_name=${_SERVICE_NAME}" -var="image_uri=${_IMAGE_URI}" -no-color
        elif [ "${_COMMAND}" = "apply" ] || [ "${_COMMAND}" = "apply -auto-approve" ]; then
          terraform apply -auto-approve -var="project_id=${PROJECT_ID}" -var="region=${_REGION}" -var="service_name=${_SERVICE_NAME}" -var="image_uri=${_IMAGE_URI}" -no-color
        else
          echo "Error: Invalid command ${_COMMAND}. Use 'plan' or 'apply'"
          exit 1
        fi
    dir: "terraform"

options:
  logging: GCS_ONLY
  logsBucket: "gs://geminiflow-461207-tfstate"

timeout: "1200s"
